### PR TITLE
Merge gh-pages branch into Master

### PR DESCRIPTION
**Pull request by rmayf**
methinks this was an accident.  There's some nice functionality in that branch that would be nice to have in mainline!

### CODE REVIEW

**Comment by Mnmhead** [comment]
> methinks this was an accident. There's some nice functionality in that branch that would be nice to have in mainline!

**Comment by Mnmhead** [comment]
How does github work wut.  Im so bad at understanding this GUI....

I think the reason the gh-pages branch is different from the master branch is because gh-pages is a special branch which github will host for you if there is a file named index.html in the repository.  Github is hosting my page at:   https://mnmhead.github.io/

Sooooo.....I think I sort of just made gh-pages my 'master' branch.  I just developed under the gh-pages branch.   Is there a nice way to keep gh-pages in sync with master?

**Comment by rmayf** [comment]
Ah I see what happened, no that makes sense why you're using the gh-pages
branch now. I think there's a setting to say gh-pages IS my master branch.
I'll track it down for you because yeah, keeping them in sync will be a
pain.

Reid

**Comment by rmayf** [comment]
https://help.github.com/en/enterprise/2.13/user/articles/setting-the-default-branch

**Pull request merged**
